apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: '6.0.1'
      sourceRef:
        kind: HelmRepository
        name: wordpress
        namespace: flux-system
      interval: 1m
